name: "x86_64-linux Nix"
on:
  pull_request:
    branches: [ "master", "dev" ]
  push:
    branches: [ "master", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git submodule update --init --recursive
    - uses: cachix/install-nix-action@v31
    - name: Check flake
      run: nix flake check ".?submodules=1#"
    - name: build BeeEngineEditor
      run: nix build ".?submodules=1#BeeEngineEditor" -L
    - name: build BeeLocalization
      run: nix build ".?submodules=1#BeeLocalization" -L