name: "Nix"
on:
  pull_request:
	branches: [ "master", "dev" ]
  push:
	branches: [ "master", "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
    - run: nix build ".?submodules=1#"
    - run: nix flake check