name: "x86_64-windows"
on:
  pull_request:
    branches: [ "master", "dev" ]
  push:
    branches: [ "master", "dev" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1    
    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.3.296.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true
    - uses: actions/checkout@v4
    - run: git submodule update --init --recursive
    - name: Run Setup.py
      run: python Setup.py
    - name: Configure
      run: cmake --preset Release-Windows
    - name: Build
      run: cmake --build build/Release --target BeeEngineEditor